#!/usr/bin/env bash

load_dotfiles() {
  local -a files=(
    ${HOME}/.bash_profile.private # Private settings not under version control
    ${HOME}/.bash.d/colors # Colors
    ${HOME}/.bash.d/utils # Utils
    ${HOME}/.bash.d/options # Options
    ${HOME}/.bash.d/exports # Exports
    ${HOME}/.bash.d/paths # Path modifications
    ${HOME}/.bash.d/prompt # Custom bash prompt
    ${HOME}/.bash.d/aliases # Aliases
    ${HOME}/.bash.d/environments # Environments
    ${HOME}/.bash.d/functions/* # Functions
    ${HOME}/.bash.d/autocompletes # Auto completes
  )

  # If these files are readable, source them
  for index in ${!files[*]}; do
    if [[ -r ${files[$index]} ]]; then
      source ${files[$index]}
    fi
  done
}

load_ssh_agent()
{
  local keys env state
  keys=(~/.ssh/*.pub)

  env=~/.ssh/agent.env
  [ ! -r "$env" ] || . "$env" >/dev/null
  ssh-add -l >/dev/null 2>&1
  state="$?"

  if [ ! "$SSH_AUTH_SOCK" ] || [ "$state" == "2" ]; then
    (umask 077; ssh-agent > "$env")
    . "$env" >/dev/null
    ssh-add "${keys[@]%%.pub}"
  elif [ "$SSH_AUTH_SOCK" ] && [ "$state" == "1" ]; then
    ssh-add "${keys[@]%%.pub}"
  fi
}

load_dotfiles
unset load_dotfiles

load_ssh_agent
unset load_ssh_agent
