#!/usr/bin/env bash

load_dotfiles() {
  local -a files=(
    ${HOME}/.bash_profile.private # Private settings not under version control
    ${HOME}/.bash.d/colors # Colors
    ${HOME}/.bash.d/utils # Utils
    ${HOME}/.bash.d/options # Options
    ${HOME}/.bash.d/exports # Exports
    ${HOME}/.bash.d/paths # Path modifications
    ${HOME}/.bash.d/prompt # Custom bash prompt
    ${HOME}/.bash.d/aliases # Aliases
    ${HOME}/.bash.d/environments # Environments
    ${HOME}/.bash.d/functions/* # Functions
    ${HOME}/.bash.d/autocompletes # Auto completes
  )

  # If these files are readable, source them
  for index in ${!files[*]}; do
    if [[ -r ${files[$index]} ]]; then
      source ${files[$index]}
    fi
  done
}

load_dotfiles
unset load_dotfiles
