" vim:foldmethod=marker:foldlevel=0
set history=1000

" use the monokai dark theme
set background=dark
colorscheme Tomorrow-Night

" make vim more useful
set nocompatible
filetype off
" {{{ Vundle
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
call vundle#begin('~/.vim/bundle')

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'
Plugin 'flazz/vim-colorschemes'

" let vim control tmux
Plugin 'benmills/vimux'
Plugin 'christoomey/vim-tmux-navigator'

" read editorconfig
Plugin 'editorconfig/editorconfig-vim'

" continuously updated session files
Plugin 'tpope/vim-obsession'

" a git wrapper so awesome, it should be illegal
Plugin 'tpope/vim-fugitive'

" enable repeating supported plugin maps with "."
Plugin 'tpope/vim-repeat'

" vim plugin for intensely orgasmic commenting
Plugin 'scrooloose/nerdcommenter'

" lean & mean status/tabline for vim that's light as air
Plugin 'bling/vim-airline'

" vim plugin, provides insert mode auto-completion for quotes, parens, brackets, etc.
Plugin 'Raimondi/delimitMate'

" unite and create user interfaces
Plugin 'shougo/unite.vim'
Plugin 'shougo/neomru.vim'
Plugin 'shougo/vimproc.vim'

" perform all your vim insert mode completions with tab
Plugin 'ervandew/supertab'

" a vim plugin which shows a git diff in the gutter and stages/reverts hunks
Plugin 'airblade/vim-gitgutter'

" quoting/parenthesizing made simple
Plugin 'tpope/vim-surround'

" syntax checking hacks for vim
Plugin 'scrooloose/syntastic'

" highlights trailing whitespace in red and provides :fixwhitespace to fix it
Plugin 'ntpeters/vim-better-whitespace'

" manage marked2 application
Plugin 'itspriddle/vim-marked'

" markdown support
Plugin 'tpope/vim-markdown'

call vundle#end()
" }}}
" {{{ Interface
" show line numbers
set number
set numberwidth=3

" break lines at word
set linebreak

" wrap-broken line prefix
set showbreak=>\

" line wrap (number of cols)
set textwidth=120

" format using textwidth, including comments and gq
set formatoptions=crq

" set lines wrap
set wrap

" highlight matching brace
set showmatch

" use visual bell (no beeping)
"set visualbell

" disable all bells
set belloff=all

" highlight all search results
set hlsearch

" enable smart-case search
set smartcase

" always case-insensitive
set ignorecase

" searches for strings incrementally
set incsearch

" enable smart-indent
set cindent

" enable smart-tabst
set smarttab

" number of spaces per Tab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" use spaces instead of tabs
set expandtab

" show row and column ruler information
set ruler
set rulerformat=%=%h%m%r%w\ %(%c%V%),%l/%L\ %P

" number of undo levels
set undolevels=1000

" backspace behaviour
set backspace=indent,eol,start

" a - terse messages (like [+] instead of [Modified]
" t - truncate file names
" i - no intro message when starting vim fileless
" t - truncate long messages to avoid having to hit a key
set shortmess=atTI

" display the number of (characters|lines) in visual mode, also cur command
set showcmd

" remove preview poping from autocompletion
set completeopt=menu

" max items in popup menu
set pumheight=8

" show fold column, fold by indent
set foldcolumn=2
set foldmethod=indent

" always show tab line
set showtabline=2

" highlight searches
set hlsearch

" highlight position of cursor
set cursorline

" show the current mode
set showmode

" show the filename in the window titlebar
set title

" show “invisible” characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list

" always show status line
set laststatus=2
set wrap
" }}}
" {{{ Behavior
" enable syntax highlighting
syntax on

" let the filetype plugins do the work.
filetype plugin on
filetype indent on

" optimize for fast terminal connections
set ttyfast

" centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
set undodir=~/.vim/undo

" don’t create backups when editing files in certain directories
set backupskip=/tmp/*,/private/tmp/*

" set to auto read when a file is changed from the outside
set autoread

" use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard=unnamed

" enhance command-line completion
set wildmenu

" allow cursor keys in insert mode
set esckeys

" add the g flag to search/replace by default
set gdefault

" use UTF-8 without BOM
set encoding=utf-8 nobomb

" ignore compiled files
set wildignore=*.o,*~,*.pyc,.git\*,.hg\*,.svn\*,.meteor

" change mapleader
let mapleader=","

" respect modeline in files
set modeline
set modelines=4

" enable per-directory .vimrc files and disable unsafe commands in them
" set exrc
" set secure

" enable mouse in all modes
set mouse=a

" disable error bells
set noerrorbells

" don’t reset cursor to start of line when moving around.
set nostartofline

" i want new splits to appear to the right and to the bottom of the current
set splitbelow
set splitright

" start scrolling three lines before the horizontal window border
set scrolloff=3

" strip trailing whitespace (,ss)
function! StripWhitespace()
  let save_cursor = getpos(".")
  let old_query = getreg('/')
  :%s/\s\+$//e
  call setpos('.', save_cursor)
  call setreg('/', old_query)
endfunction
noremap <leader>ss :call StripWhitespace()<CR>

" specify the behavior when switching between buffers
try
  set switchbuf=useopen,usetab,newtab
  set stal=2
catch
endtry

" return to last edit position when opening files
autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal! g`\"" |
      \ endif

" window movement shortcuts
" move to the window in the direction shown, or create a new window
function! WinMove(key)
  let t:curwin = winnr()
  exec "wincmd ".a:key
  if (t:curwin == winnr())
    if (match(a:key,'[jk]'))
      wincmd v
    else
      wincmd s
    endif
    exec "wincmd ".a:key
  endif
endfunction

" remember info about open buffers on close
set viminfo^=%
" }}}
" {{{ Plugins
" to ensure that this plugin works well with Tim Pope's fugitive
" if you wanted to avoid loading EditorConfig for any remote files over ssh
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']

" unite
let g:unite_source_history_yank_enable=1
call unite#filters#matcher_default#use(['matcher_fuzzy'])
nnoremap <leader>t :Unite -buffer-name=files -start-insert file_rec/async:!<cr>
nnoremap <leader>f :Unite -buffer-name=files -start-insert file<cr>
nnoremap <leader>m :Unite -buffer-name=mru -start-insert file_mru<cr>
nnoremap <leader>r :Unite -buffer-name=register -start-insert register<cr>
nnoremap <leader>o :Unite -buffer-name=outline -start-insert outline<cr>
nnoremap <leader>y :Unite -buffer-name=yank history/yank<cr>
nnoremap <leader>b :Unite -buffer-name=buffer buffer<cr>

" airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" supertab
let g:SuperTabDefaultCompletionType = 'context'
" }}}
" {{{ Autocommand
if has('autocmd') && !exists('autocommands_loaded')
  let autocommands_loaded = 1
  autocmd FileType html setlocal ts=2 sts=2 sw=2 et indentkeys-=*<return>
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noet
  autocmd FileType markdown,textile,gitcommit setlocal tw=0 wm=0 wrap spell
endif
"}}}
" {{{ Maps
" disable Ex mode
noremap Q <NOP>

" helpers for dealing with other people's code
nmap \t4 :set ts=4 sts=4 sw=4 noet<cr>
nmap \t2 :set ts=2 sts=2 sw=2 noet<cr>
nmap \s4 :set ts=4 sts=4 sw=4 et<cr>
nmap \s2 :set ts=2 sts=2 sw=2 et<cr>

" word under cursor
nnoremap * *<C-O>:%s///gn<CR>

" jump to tags
nnoremap <C-g> <C-]>

" refactor all file
noremap <leader>= ggVG=

" wipout buffer
nmap <silent> <leader><leader>b :bw<cr>

" fold/Unfold map
noremap <space> za

" remap C-space to completion
inoremap <C-Space> <C-x><C-o>
inoremap <C-@> <C-Space>

" clear highlighted search
noremap <leader><space> :set hlsearch! hlsearch?<cr>

" toggle paste mode
map <leader>v :set paste!<cr>
map <leader>V :set nopaste!<cr>

" edit vim config
map <leader>ev :e! ~/.vimrc<cr>
" edit gitconfig
map <leader>eg :e! ~/.gitconfig<cr>
" edit tmux config
map <leader>et :e! ~/.tmux.conf<cr>

" enable . command in visual mode
vnoremap . :normal .<cr>

" smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
nnoremap <silent> <leader><C-h> :call WinMove('h')<cr>
nnoremap <silent> <leader><C-j> :call WinMove('j')<cr>
nnoremap <silent> <leader><C-k> :call WinMove('k')<cr>
nnoremap <silent> <leader><C-l> :call WinMove('l')<cr>

" search for word under the cursor
nnoremap <leader>/ "fyiw :/<c-r>f<cr>

" save a file as root (,W)
noremap <leader>W :w !sudo tee % > /dev/null<CR>

" useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader><leader>t :tabnext<cr>

" fugitive Shortcuts
nmap <leader>ge :Gedit<cr>
nmap <silent> <leader>gc :Gcommit<cr>
nmap <silent> <leader>gb :Gblame<cr>
nmap <silent> <leader>gr :Gread<cr>
nmap <silent> <leader>gs :Gstatus<cr>
nmap <silent> <leader>gw :Gwrite<cr>

" marked2 shortcuts
nmap <leader>mo :MarkedOpen!<cr>
nmap <leader>mq :MarkedQuit<cr>

" switch between current and last buffer
nmap <leader>. <c-^>

" let 'tl' toggle between this and the last accessed tab
let g:lasttab = 1
nmap <leader>tl :exe "tabn ".g:lasttab<cr>
au TabLeave * let g:lasttab = tabpagenr()

" opens a new tab with the current buffer's path
" super useful when editing files in the same directory
map <leader>oe :e <C-R>=expand("%:p:h") . "/" <CR>
map <leader>ot :tabe <C-R>=expand("%:p:h") . "/" <CR>
map <leader>os :split <C-R>=expand("%:p:h") . "/" <CR>
map <leader>ov :vsplit <C-R>=expand("%:p:h") . "/" <CR>

" switch CWD to the directory of the open buffer
map <leader>cd :cd %:p:h<cr>:pwd<cr>

" remap VIM 0 to first non-blank character
map 0 ^

" tweak ESC to be 'jk' typed fast
imap jk <ESC>

" prompt for a command to run
map <Leader>vp :VimuxPromptCommand<CR>

" run last command executed by VimuxRunCommand
map <leader>vl :VimuxRunLastCommand<CR>

" inspect runner pane map
map <leader>vi :VimuxInspectRunner<CR>

" close vim tmux runner opened by VimuxRunCommand
map <Leader>vq :VimuxCloseRunner<CR>

" interrupt any command running in the runner pane map
map <leader>vs :VimuxInterruptRunner<CR>
" }}}
" {{{ Misc
" remove the Windows ^M - when the encodings gets messed up
noremap <leader><leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm
" }}}
" {{{ Command Line
" smart mappings on the command line
cno $h ~/
cno $d ~/Desktop/
cno $c ./
cno $b ~/.bash.d/
cno $w ~/Workspaces/
cno $s ~/Sites/

" bash like keys for the command line
cnoremap <C-A> <Home>
cnoremap <C-E> <End>
cnoremap <C-K> <C-U>
cnoremap <C-P> <Up>
cnoremap <C-N> <Down>
"}}}
