#!/bin/bash

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Reload the shell (i.e. invoke as a login shell)
alias reload='exec $SHELL -l'

# Easier navigation: .., ..., ...., ....., ~ and -
alias cd..='cd ..'
alias ~="cd ~"
alias -- -='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'

# Shortcuts
alias desktop='cd ~/Desktop'
alias downloads='cd ~/Downloads'
alias sites='cd ~/Sites/projects'
alias workspaces='cd ~/Workspaces'
alias icloud='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs/'

# So lazy am i
alias g='git'
alias h='history'
alias j='jobs'
alias vg='vagrant'
alias activate='source venv/bin/activate'

# Update commands
alias up-osx='sudo softwareupdate -i -a'
alias up-brew='brew update && brew upgrade && brew cleanup && brew cask cleanup && brew doctor'
alias up-pip='gpip install --upgrade pip setuptools virtualenv wheel ipython'
alias up-all='up-osx; up-brew; up-pip;'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag='--color'
else # OS X `ls`
  colorflag='-G'
fi

# List all files colorized in long format
alias l='ls -lhFG'
# List all files colorized ordered by last modified
alias lt="ls -tG"
# List all files colorized in long format, including dot files
alias la='ls -lhAFG'
# List only directories
alias lsd='ls -lhFG | grep --color=never '^d''
# Always use color output for `ls`
alias ls='ls -G'

# Shortcut to remove all with force
alias rmf='rm -rf'

# Folder manipulation
alias md='mkdir -p'
alias rd='rmdir'
alias d='dirs -v | head -10'

# Always use color output for `grep`
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# tmux aliases
alias ta='tmux attach'
alias tls='tmux ls'
alias tat='tmux attach -t'
alias tns='tmux new-session -s'

# Print path directories
alias path='echo -e ${PATH//:/\\n}'

# Recommended 'top' invocation to minimize resources
alias ttop='top -R -F -s 10 -o rsize'

# Get week number
alias week='date +%V'

# Stopwatch
alias timer='e_header "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map='xargs -n1'

# Trim new lines and copy to clipboard
alias c='tr -d "\n" | pbcopy'

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | e_success 'Public key copied to pasteboard.'"

# Usage: cppcompile main.cpp
alias cppcompile='c++ -std=c++11 -stdlib=libc++'

# IP addresses
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias localip='ipconfig getifaddr en1'
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show all open TCP/IP sockets
alias netcons='sudo lsof -i'

# Flush out the DNS Cache
alias flushdns='dscacheutil -flushcache'

# Display open sockets
alias lsock='sudo lsof -i -P'

# Display only open UDP sockets
alias lsock-ucp='sudo lsof -nP | grep UDP'

# Display only open TCP sockets
alias lsock-tcp='sudo lsof -nP | grep TCP'

# Get info on connections for en0
alias ipinfo-en0='ipconfig getpacket en0'

# Get info on connections for en1
alias ipinfo-en1='ipconfig getpacket en1'

# All listening connections
alias lsock-opened='sudo lsof -i | grep LISTEN'

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias cleanup-ls='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder'

# Recursively delete `.DS_Store` files
alias cleanup-ds="find . -type f -name '*.DS_Store' -ls -delete"

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd='hexdump -C'

# OS X has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum='md5'

# OS X has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum='shasum'

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK)
alias afk='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl'

# Show/hide hidden files in Finder
alias hidefiles='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
alias showfiles='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias showdesktop='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias volumeoff='osascript -e "set volume output muted true"'
alias volumeon='osascript -e "set volume 7"'
