#!/usr/bin/env bash

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Reload the shell (i.e. invoke as a login shell)
alias reload='exec $SHELL -l'

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..='cd ..'
alias ...='cd ../..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'

# Shortcuts
alias desktop='cd ~/Desktop'
alias documents='cd ~/Documents'
alias downloads='cd ~/Downloads'
alias workspaces='cd ~/Workspaces'
alias projects='cd ~/Projects'

# Python virtualenv
alias activate='[ -e .venv/bin/activate ] && . .venv/bin/activate'

# Because it's so much nicer
alias g="git"
alias d='dirs -v'
alias edit="$EDITOR"
alias view="vim -R"
alias tree="tree -a -I '.git|.svn|node_modules|.venv|__pycache__|*.pyc' --dirsfirst"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag='--color'
else # OS X `ls`
  colorflag='-G'
fi

# List all files colorized in long format
alias ll="ls -lhF $colorflag"
# List all files colorized ordered by last modified
alias lt="ls -lhFt $colorflag"
# List all files colorized in long format, including dot files
alias la="ls -lhAF $colorflag"
# List only directories
alias lsd="ls -lhF $colorflag | grep --color=never '^d'"
# Always use color output for `ls`
alias ls="ls $colorflag"
# Sort files with increasing version numbers.
alias lv="ls | sort --version-sort"
unset colorflag

# Always use color output for `grep` and ignore directories.
grepflags='--color=auto --exclude-dir={.bzr,.git,.hg,.svn,.venv,venv}'
alias grep="grep $grepflags"
alias egrep="egrep $grepflags"
alias fgrep="fgrep $grepflags"
unset grepflags

# Tmux aliases
alias ta='tmux attach'
alias tat='tmux attach -t'
alias tls='tmux list-sessions'
alias tns='tmux new-session -s'
alias tstart='tmux start-server'

# Print path directories
alias path='echo -e ${PATH//:/\\n}'

# Recommended 'top' invocation to minimize resources
alias ttop='top -R -F -s 10 -o rsize'

# Get week number
alias week='date +%V'

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map='xargs -n1'

# Trim new lines and copy to clipboard
alias trcopy='tr -d "\n" | clip'

# URL-encode strings
alias urlencode='python -c "import sys, urllib; print urllib.quote_plus(sys.argv[1]);"'
