#!/usr/bin/env bash

# Load bash completions.
_load_completions() {
    # Load completion installed via Homebrew
    [ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

    # Load completion installed in this repository
    local dir=$HOME/.bash.d/completions
    if [ -d "$dir" ] && [ -x "$dir" ]; then
        for i in $(LC_ALL=C command ls "$dir"); do
            [ -f "$dir/$i" ] && . "$dir/$i"
        done
    fi
}
_load_completions

# Add completion for marks shortcuts
_completemarks() {
  local curw=${COMP_WORDS[COMP_CWORD]}
  local wordlist=$(find $MARKPATH -type l | awk -F"/" '{printf "%s ",$NF}')
  COMPREPLY=($(compgen -W '${wordlist[@]}' -- "$curw"))
  return 0
}
complete -F _completemarks jump unmark

# Add completion for SSH hosts
_completehosts() {
  local curw=${COMP_WORDS[COMP_CWORD]}
  local config_hosts known_hosts
  if [ -e "$HOME/.ssh/config" ]
  then
    config_hosts=$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')
  fi
  if [ -e "$HOME/.ssh/known_hosts" ]
  then
    known_hosts=$(cut -f 1 -d ' ' ~/.ssh/known_hosts | sed -e s/,.*//g | uniq | grep -v ':')
  fi
  wordlist=$(echo "${config_hosts[@]}" "${known_hosts[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
  COMPREPLY=($(compgen -W '${wordlist[@]}' -- "$curw"))
}
complete -F _completehosts ssh

# Enable pip command autocompletion for `gpip3` alias as well
complete -o "default" -o "nospace" -F _pip gpip3

# Enable git command autocompletion for 'g' as well
__git_complete g __git_main

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Calendar Contacts Dock Finder Mail Music Safari SystemUIServer Terminal" killall

# Add `license` tab completion
complete -o "nospace" -W "mit apache2 gpl2" license

# Add `load` tab completion
complete -o "nospace" -W "docker rvm nvm" load

# Add `gitlab` tab completion
complete -o "nospace" -W "pipelines" gitlab

# Add 'go' tab completion
complete -C "gocomplete" go
