#!/usr/bin/env bash

# Add completion for marks shortcuts
_completemarks() {
  local curw=${COMP_WORDS[COMP_CWORD]}
  local wordlist=$(find $MARKPATH -type l | awk -F"/" '{printf "%s ",$NF}')
  COMPREPLY=($(compgen -W '${wordlist[@]}' -- "$curw"))
  return 0
}
complete -F _completemarks jump unmark

# Enable vagrant command autocompletion for `vg` alias as well
complete -o default -F _vagrant vg

# Enable pip command autocompletion for `gpip` alias as well
complete -o default -F _pip gpip

# Enable git command  autocompletion for 'g' as well
complete -o default -o nospace -F _git g

# Enable Tab completion to select options
# bind 'set show-all-if-ambiguous on'
# bind 'TAB:menu-complete'

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults;

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall;

# Add `license` tab completion
complete -o "nospace" -W "mit apache2 gpl2" license;

# Add `gitlab` tab completion
complete -o "nospace" -W "pipelines" gitlab;
