#!/bin/bash

# Set colors
tput sgr0; # reset colors
reset=$(tput sgr0);
bold=$(tput bold);
underline=$(tput sgr 0 1);
black=$(tput setaf 0);
tan=$(tput setaf 3)
blue=$(tput setaf 33);
cyan=$(tput setaf 37);
green=$(tput setaf 70);
orange=$(tput setaf 166);
purple=$(tput setaf 125);
red=$(tput setaf 124);
violet=$(tput setaf 61);
white=$(tput setaf 15);
yellow=$(tput setaf 136);
