#!/usr/bin/env bash

# Load docker environment
function load_docker() {
  if [[ -z "$DOCKER_HOST" ]]; then
    if type_exists 'docker-machine'; then
      local machine="docker"
      # Load docker machine environment
      eval $(docker-machine env $machine)
      # Get docker machine IP address
      local ip="$(docker-machine ip $machine 2>/dev/null)"
      if [[ -n "$ip" ]]; then
        if ! grep "$ip" /etc/hosts >>/dev/null; then
          # Clear existing docker.local entry from /etc/hosts
          sudo sed -i "" "/[[:space:]]$machine\.local$/d" /etc/hosts
          # Add docker machine IP to hosts
          sudo /usr/bin/env bash -c "echo \"$ip	$machine.local\" >> /etc/hosts"
        fi
      fi
    fi
  fi
}

# Load nvm environment along with bash completion
function load_nvm() {
  if [[ -n "$NVMPATH" ]]; then
    local -a files=(
      ${NVMPATH}/nvm.sh
      ${NVMPATH}/bash_completion
    )

    # If these files are readable, source them
    for index in ${!files[*]}; do
      if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
      fi
    done
  fi
}

# Load rvm environment along with bash completion
function load_rvm() {
  if [[ -n "$RVMPATH" ]]; then
    local -a files=(
      ${RVMPATH}/scripts/rvm
      ${RVMPATH}/scripts/completion
    )

    # If these files are readable, source them
    for index in ${!files[*]}; do
      if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
      fi
    done
  fi
}

# Function to load an environment
# $1 = environment name
function load() {
  local loader="load_$1"
  if type_exists "$loader"; then
    eval "$loader"
    return 1
  fi
  return 0
}
