#!/bin/bash

# In case we want to use it somewhere
export DOTFILES_DIRECTORY="${HOME}/.dotfiles"

# Make vim the default editor
export EDITOR="vim"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Set .marks as the folder for jumping symlinks
export MARKPATH=$DOTFILES_DIRECTORY/marks

# Define databases
export PGDATA=/usr/local/var/postgres
export MYSQLDATA=/usr/local/var/mysql
export MONGODATA=/usr/local/var/mongo

# Define Lua paths
export LUA_PATH="/usr/local/lua/share/lua/5.3/?.lua;;"
export LUA_CPATH="/usr/local/lua/lib/lua/5.3/?.so;;"
