#!/usr/bin/env bash

# Tell readline where to find configuration
export INPUTRC=$HOME/.inputrc

# In case we want to use it somewhere
export DOTFILES_DIRECTORY=$HOME/.dotfiles

# Make neovim the default editor
export EDITOR="nvim"

# Larger bash history (allow 32^3 entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:jrnl *"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true

# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Set .marks as the folder for jumping symlinks
export MARKPATH=$DOTFILES_DIRECTORY/marks

# Define database paths
export PGDATA=/usr/local/var/postgres
export MYSQLDATA=/usr/local/var/mysql
export MONGODATA=/usr/local/var/mongo

# Define Lua paths
export LUA_PATH="/usr/local/lua/share/lua/5.3/?.lua;;"
export LUA_CPATH="/usr/local/lua/lib/lua/5.3/?.so;;"

# Use globally installed package in Node
export NODE_PATH=/usr/local/lib

# For pkg-config to find additional softwares
# export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH"
# export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig:$PKG_CONFIG_PATH"

# Tell nvm where is the working directory
export NVM_DIR=$HOME/.nvm
export NVMPATH=$NVM_DIR

# Tell rvm where is the working directory.
export RVMPATH=$HOME/.rvm

# Tell go where is the working directory
export GOPATH=$HOME/Workspaces/go

# Tell Espressif toolchain where to find the SDK
export IDF_PATH=/usr/local/Espressif/esp-rtos-sdk
