#!/usr/bin/env bash

# Reset PATH on top
PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
  '/usr/local/opt/llvm/bin' # Add brewed LLVM
  '/usr/local/opt/openssl/bin' # Add brewed OpenSSL
  '/usr/local/opt/qt/bin' # Add brewed Qt
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}; do
  if [ -d "${dirs_to_prepend[$index]}" ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dirs_to_prepend[$index]}:$PATH"
  fi
done
unset dirs_to_prepend

# Directories to be appended to PATH
declare -a dirs_to_append=(
  '/usr/local/texlive/2019/bin/x86_64-darwin' # Add brewed TexLive
  '/usr/local/CrossPack-AVR/bin' # Add brewed avr toolchain
  '/usr/local/Espressif/xtensa-lx106-elf/bin' # Add installed xtensa toolchain
)

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
  if [ -d "${dirs_to_append[$index]}" ]; then
    # If these bins exist, then append them to existing PATH
    PATH="$PATH:${dirs_to_append[$index]}"
  fi
done
unset dirs_to_append

export PATH
