#!/bin/bash

# bash_paths

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    "$(brew --prefix)/bin" # Add installed Homebrew binaries
    "$(brew --prefix)/sbin" # Add installed Homebrew binaries
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/bin" # Add user binaries
    "$DOTFILES_DIRECTORY/bin" # Add dotfiles binaries
    "$RBENV_ROOT/bin" # Add rbenv binaries
    "$JENV_ROOT/bin" # Add jenv binaries
    "$NPM_ROOT/bin" # Add npm packages binaries
    "$GOPATH/bin" # Add go binaries
    "$GCC_ARM_NONE_EABI_ROOT/bin" # Add gcc arm toolchain
    "/usr/local/nrfjprog" # Add nrf5x command line tools
    # "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
    if [ -d ${dirs_to_prepend[$index]} ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:$PATH"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing PATH
        PATH="$PATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH
