#!/bin/bash

# Reset PATH on top
PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
  '/usr/local/gcc-arm-none-eabi-4_9-2015q2/bin/' # Add gcc arm
  '/usr/local/flatbuffers/bin' # Add flatc
  '/usr/local/lua/bin' # Add lua 5.3
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}; do
  if [ -d ${dirs_to_prepend[$index]} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dirs_to_prepend[$index]}:$PATH"
  fi
done
unset dirs_to_prepend

# Directories to be appended to PATH
declare -a dirs_to_append=(
)

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
  if [ -d ${dirs_to_append[$index]} ]; then
    # If these bins exist, then append them to existing PATH
    PATH="$PATH:${dirs_to_append[$index]}"
  fi
done
unset dirs_to_append

export PATH
