#!/usr/bin/env bash

brew_tap() {
  local -a taps=(
    'goles/battery'
    'homebrew/bundle'
    'homebrew/cask'
    'homebrew/services'
  )

  # Install all taps
  # brew tap command only accept one tap repo at a time
  for tap in ${taps[@]}; do
    e_info "Tapping $tap"
    brew tap $tap
  done
}

brew_formulae() {
  local -a formulae=(
    'ack'
    'astyle'
    'autoconf'
    'automake'
    'bash'
    'bash-completion'
    'battery'
    'binutils'
    'cmake'
    'ctags'
    'cscope'
    'curl'
    'ffmpeg'
    'freetype'
    'fzf'
    'git'
    'htop-osx'
    'imagemagick'
    'libxml2'
    'libyaml'
    'lua'
    'mcrypt'
    'neovim'
    'ngrep'
    'nmap'
    'openssl'
    'pip-completion'
    'pkg-config'
    'python'
    'python3'
    'readline'
    'reattach-to-user-namespace'
    'rename'
    'rsync'
    'ruby'
    'sdl2'
    'sqlite'
    'ssh-copy-id'
    'tmux --HEAD'
    'tmuxinator-completion'
    'tree'
    'vim'
    'wget'
    'zlib'
  )

  # Install all formulae
  for formula in ${formulae[@]}; do
    e_info "Brewing $formula"
    brew install $formula
  done
}

brew_cask() {
  local -a casks=(
    'provisionql'
    'qlcolorcode'
    'qlimagesize'
    'qlmarkdown'
    'qlprettypatch'
    'qlstephen'
    'qlvideo'
    'quicklook-csv'
    'quicklook-json'
    'suspicious-package'
    'webpquicklook'
  )

  # Install all casks
  for cask in ${casks[@]}; do
    e_info "Casking $cask"
    brew cask install $cask
  done
}

run_softwares() {
  if type_exists 'brew'; then
    e_header "Updating Homebrew"

    # Check everything is fine
    brew doctor
    [[ $? ]] && e_success "Done"

    # Use the latest version of Homebrew
    brew update
    [[ $? ]] && e_success "Done"

    e_header "Updating any existing Homebrew formulae"
    brew upgrade
    [[ $? ]] && e_success "Done"

    e_header "Taping Homebrew"
    brew_tap
    [[ $? ]] && e_success "Done"

    e_header "Installing Homebrew formulae"
    brew_formulae
    [[ $? ]] && e_success "Done"

    e_header "Installing Cask formulae"
    brew_cask
    [[ $? ]] && e_success "Done"

    # Remove outdated versions from the Cellar
    brew cleanup
  else
    e_warn "Homebrew not found. Brew packages installation skipped."
    exit 0
  fi
}
