#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew"
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae"
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        e_header "Taping Homebrew"
        local -a taps=(
            'caskroom/cask'
            'goles/battery'
            'homebrew/apache'
            'homebrew/completions'
            'homebrew/dupes'
            'homebrew/nginx'
            'homebrew/php'
            'homebrew/python'
            'homebrew/science'
            'homebrew/services'
            'homebrew/tex'
            'homebrew/versions'
            'homebrew/x11'
        )

	# Convert the array of taps into a list of space-separated strings
	local tap_list = $( printf "%s " "${taps[@]}" )

	# Install all taps
	brew tap $list
	[[ $? ]] && e_success "Done"

        e_header "Installing Homebrew formulae"
        local -a formulae=(
            'bash'
            'bash-completion'
            'battery'
            'curl'
            'ffmpeg'
            'git'
            'rsync'
            'htop-osx'
            'imagemagick'
            'libxml2'
            'mcrypt'
            'openssl'
            'mysql'
            'ngrep'
            'nmap'
            'pip-completion'
            'pkg-config'
            'postgresql'
            'python'
            'python3'
            'readline'
            'reattach-to-user-namespace'
            'rename'
            'sqlite'
            'ssh-copy-id'
            'subversion'
            'tmux'
            'tmuxinator-completion'
            'tree'
            'unrar'
            'vagrant-completion'
            'vim --override-system-vi'
            'wget --with-iri'
            'heroku-toolbelt'
        )

	# Convert the array of formula into a list of space-separated strings
	local formulae_list = $( printf "%s " "${formulae[@]}" )

	# Install all formulae
	brew install $formulae_list
	[[ $? ]] && e_success "Done"

        e_header "Installing Cask formulae"
        local -a casks=(
            'qlcolorcode'
            'qlstephen'
            'qlmarkdown'
            'quicklook-json'
            'qlprettypatch'
            'quicklook-csv'
            'betterzipql'
            'qlimagesize'
            'webpquicklook'
            'suspicious-package'
            'provisionql'
            'xquartz'
        )

	# Convert the array of casks into a list of space-separated strings
	local cask_list = $( printf "%s " "${casks[@]}" )

	# Install all casks
	brew cask install $formulae_list
	[[ $? ]] && e_success "Done"

        # Remove outdated versions from the Cellar
        brew cleanup

    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}
