#!/bin/bash

run_gem() {

    # Check for gem
    if type_exists 'gem'; then
        e_header "Installing Ruby gems"

        # List of gem packages
        local packages=$(cat "$DOTFILES_DIRECTORY"/installed/Gemfile | tr -s '\n' ' ')

        # Install packages globally and quietly
        gem install $packages --quiet

        [[ $? ]] && e_success "Done"
    else
        printf "\n"
        e_error "Error: gem not found."
        printf "Aborting...\n"
        exit
    fi

}
