#!/bin/bash

run_help() {
  cat <<EOT
OS X dotfiles - Hugo Rodde

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    --no-packages   Suppress package updates
    --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/roddehugo/dotfiles/

Copyright (c) Hugo Rodde
Licensed under the MIT license.
EOT
}
