#!/bin/bash

run_pip() {
  if type_exists "$1"; then
    e_header "Installing $1 modules"

    # List of pip packages
    local -a packages=(
      'pip'
    )

    # Install packages globally and quietly
    eval "g$1 install --upgrade $( printf "%s " "${packages[@]}" )"
    [[ $? ]] && e_success "Done"
  else
    e_warn "$1 not found. Skipping."
    exit 0
  fi
}
