#!/usr/bin/env bash

run_pip() {
  if type_exists 'python3'; then
    e_header "Installing pip modules"

    # List of pip packages
    local -a packages=(
      'pip'
      'setuptools'
      'virtualenv'
      'ipython'
      'pynvim'
    )

    # Install packages globally and quietly
    python3 -m pip install --upgrade $( printf "%s " "${packages[@]}" )
    [[ $? ]] && e_success "Done"
  else
    e_warning "python3 not found. Skipping."
    exit 0
  fi
}
