#!/usr/bin/env bash

# Recursive git command in subfolders
function git-recursive() {
  find . -type d -name '.git' | sort | while read -r dir; do
    sh -c "echo \"\ngit status: ${dir//\.git/}\" && git -C $dir/.. ${@}"
  done
}
