#!/usr/bin/env bash

# Shorthand for tree with hidden files and color enabled
function t() {
  TREEIGNORE=".git|.svn|node_modules|.venv|__pycache__|*.pyc"
  tree -aC -I "$TREEIGNORE" --dirsfirst "$@" | less -FRNX;
}
